### ISSUE TITLE
Issue installing logstash on centos 7 (AWS)

### ISSUE THREAD

**Issue by angelbarrera92** [geerlingguy/ansible-role-logstash#44]
Hi. 

First of all thanks for this awesome job. 

I am trying to use this role to install logstash along with filebeat and java. My playbook looks like: 

```yaml
---
- name: My awesome machine
  hosts: all
  become: true
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.logstash
      logstash_install_plugins:
        - logstash-input-beats
        - logstash-output-amazon_es
    - role: geerlingguy.filebeat
      filebeat_output_logstash_enabled: false
      filebeat_enable_logging: true
      filebeat_log_level: info
      filebeat_create_config: false
      filebeat_prospectors:
        - input_type: log
          paths:
            - "/var/lib/docker/containers/*/*.log"
          json.message_key: log
          json.keys_under_root: true
          processors:
            - add_docker_metadata: ~
```

The output says: 
```bash
TASK [geerlingguy.logstash : Get list of installed plugins.] **********************************************************************************************************************************
fatal: [ec2-XX-XXX-XXX-XXX.eu-central-1.compute.amazonaws.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ec2-XX-XXX-XXX-XXX.eu-central-1.compute.amazonaws.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_1fjH5w/ansible_module_command.py\", line 271, in <module>\r\n    main()\r\n  File \"/tmp/ansible_1fjH5w/ansible_module_command.py\", line 217, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/opt/logstash'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

The machine has not the `/opt/logstash` directory. So the script fails. 
I will try to fix it in a fork.

Thanks!
